name: HomeWizard P1 Emulator
version: "1.0.0"
slug: homewizard_emulator
description: "Emuleert een HomeWizard Wi‑Fi P1 API (lokale /api/v1/data) voor Alfen Wallbox load balancing"
arch:
  - amd64
  - armv7
  - armhf
  - aarch64
startup: services
boot: auto
options:
  ha_url: "http://supervisor/core/api"
  token: ""
  port: 80
  sensor_active_power_kw: "sensor.electricity_meter_huidig_gemiddelde_vraag"
  sensor_prod_kw: "sensor.electricity_meter_energieproductie"
  sensor_prod_t1_kwh: "sensor.electricity_meter_energieproductie_tarief_1"
  sensor_prod_t2_kwh: "sensor.electricity_meter_energieproductie_tarief_2"
  sensor_cons_t1_kwh: "sensor.electricity_meter_energieverbruik_tarief_1"
  sensor_cons_t2_kwh: "sensor.electricity_meter_energieverbruik_tarief_2"
  sensor_current_l1_a: "sensor.electricity_meter_stroom_fase_l1"
  sensor_current_l2_a: "sensor.electricity_meter_stroom_fase_l2"
  sensor_current_l3_a: "sensor.electricity_meter_stroom_fase_l3"
  sensor_voltage_l1_v: "sensor.electricity_meter_spanning_fase_l1"
  sensor_voltage_l2_v: "sensor.electricity_meter_spanning_fase_l2"
  sensor_voltage_l3_v: "sensor.electricity_meter_spanning_fase_l3"
  sensor_prod_l1_kw: "sensor.electricity_meter_energieproductie_fase_l1"
  sensor_prod_l2_kw: "sensor.electricity_meter_energieproductie_fase_l2"
  sensor_prod_l3_kw: "sensor.electricity_meter_energieproductie_fase_l3"
  sensor_cons_l1_kw: "sensor.electricity_meter_energieverbruik_fase_l1"
  sensor_cons_l2_kw: "sensor.electricity_meter_energieverbruik_fase_l2"
  sensor_cons_l3_kw: "sensor.electricity_meter_energieverbruik_fase_l3"
  sensor_timestamp: "sensor.electricity_meter_tijdstip"
  sensor_gas_m3: "sensor.gas_meter_gasverbruik"
schema:
  ha_url: str
  token: str
  port: int
  sensor_active_power_kw: str
  sensor_prod_kw: str
  sensor_prod_t1_kwh: str
  sensor_prod_t2_kwh: str
  sensor_cons_t1_kwh: str
  sensor_cons_t2_kwh: str
  sensor_current_l1_a: str
  sensor_current_l2_a: str
  sensor_current_l3_a: str
  sensor_voltage_l1_v: str
  sensor_voltage_l2_v: str
  sensor_voltage_l3_v: str
  sensor_prod_l1_kw: str
  sensor_prod_l2_kw: str
  sensor_prod_l3_kw: str
  sensor_cons_l1_kw: str
  sensor_cons_l2_kw: str
  sensor_cons_l3_kw: str
  sensor_timestamp: str
  sensor_gas_m3: str
